name: Playwright UI Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'demo-realworld-show/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'demo-realworld-show/**'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.49.0-noble

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Playwright Tests
      working-directory: demo-realworld-show
      run: |
        mvn clean
        mvn test -DHEADLESS=true